### ISSUE TITLE
Error decoding horizon.Problem: EOF

### ISSUE THREAD

**Issue by PedityOfficial** [lightyeario/kelp#27]
## Describe the bug
After running kelp for 1 day, we are seeing a weird bug
```
2018/10/17 18:32:16 error decoding horizon.Problem: EOF
2018/10/17 18:32:16 Can't load offers: error decoding horizon.Problem: EOF
2018/10/17 18:32:16 error decoding horizon.Problem: EOF
2018/10/17 18:32:16 Can't load offers: error decoding horizon.Problem: EOF
2018/10/17 18:32:16 error: cannot load offers to compute liabilities for asset (native): error decoding horizon.
Problem: EOF
2018/10/17 18:32:16 liabilities after resetting
2018/10/17 18:32:16 Can't load offers: error decoding horizon.Problem: EOF
2018/10/17 18:32:16 error: cannot load offers to compute liabilities for asset (native): error decoding horizon.
Problem: EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x75a9bb]
goroutine 1 [running]:
github.com/lightyeario/kelp/plugins.(*SDEX).logLiabilities(0xc420154120, 0x8b18ad, 0x6, 0x0, 0x0, 0x0, 0x0)
        /Users/nikhilsaraf/dev/go/src/github.com/lightyeario/kelp/plugins/sdex.go:435 +0xfb
github.com/lightyeario/kelp/plugins.(*SDEX).LogAllLiabilities(0xc420154120, 0x8b18ad, 0x6, 0x0, 0x0, 0x0, 0x0, 0
x8b83f4, 0x10, 0xc42023cc28, ...)
        /Users/nikhilsaraf/dev/go/src/github.com/lightyeario/kelp/plugins/sdex.go:443 +0x65
github.com/lightyeario/kelp/trader.(*Trader).update(0xc42011fc48)
        /Users/nikhilsaraf/dev/go/src/github.com/lightyeario/kelp/trader/trader.go:105 +0x1e9
github.com/lightyeario/kelp/trader.(*Trader).Start(0xc42011fc48)
        /Users/nikhilsaraf/dev/go/src/github.com/lightyeario/kelp/trader/trader.go:67 +0x6f
github.com/lightyeario/kelp/cmd.init.4.func1(0xb447e0, 0xc420061740, 0x0, 0x6)
        /Users/nikhilsaraf/dev/go/src/github.com/lightyeario/kelp/cmd/trade.go:109 +0x9d2
github.com/lightyeario/kelp/vendor/github.com/spf13/cobra.(*Command).execute(0xb447e0, 0xc4200616e0, 0x6, 0x6, 0
xb447e0, 0xc4200616e0)
        /Users/nikhilsaraf/dev/go/src/github.com/lightyeario/kelp/vendor/github.com/spf13/cobra/command.go:702 +
0x2c6
github.com/lightyeario/kelp/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xb44e40, 0x403dfc, 0xc42006a058, 
0x0)
        /Users/nikhilsaraf/dev/go/src/github.com/lightyeario/kelp/vendor/github.com/spf13/cobra/command.go:783 +
0x2e4
github.com/lightyeario/kelp/vendor/github.com/spf13/cobra.(*Command).Execute(0xb44e40, 0x0, 0x7b1582)
        /Users/nikhilsaraf/dev/go/src/github.com/lightyeario/kelp/vendor/github.com/spf13/cobra/command.go:736 +
0x2b
main.main()
        /Users/nikhilsaraf/dev/go/src/github.com/lightyeario/kelp/main.go:10 +0x2d
```

## Expected behavior
It might be possible that horizon was not responding or some library is missing.
Restarting the bot worked fine though.

## Frequency
The frequency is: Unpredictable

## Steps To Reproduce
It is very rare issue, We can give run log if it is required.
Here are the steps to reproduce the issue (see attachments in section below):
1. Set up your configuration file with these parameters:  
```
2018/10/16 07:36:55 Starting Kelp Trader: v1.0.0 [e2c473c2e866a9b27d485c403a14a4e286b51c7d]
2018/10/16 07:36:55 configs:
2018/10/16 07:36:55      SOURCE_SECRET_SEED: 
2018/10/16 07:36:55      TRADING_SECRET_SEED: [secret key to account GDGYAYBTNY6CXA77EJ2PTBJB3DR2MYFOE57I2GZYIH7
FGOHSPI4XGDVD]
2018/10/16 07:36:55      ASSET_CODE_A: XLM
2018/10/16 07:36:55      ISSUER_A: 
2018/10/16 07:36:55      ASSET_CODE_B: PEDI
2018/10/16 07:36:55      ISSUER_B: GBVUDZLMHTLMZANLZB6P4S4RYF52MVWTYVYXTQ2EJBPBX4DZI2SDOLLY
2018/10/16 07:36:55      TICK_INTERVAL_SECONDS: 300
2018/10/16 07:36:55      HORIZON_URL: https://horizon.stellar.org
2018/10/16 07:36:55 Trading XLM: for PEDI:GBVUDZLMHTLMZANLZB6P4S4RYF52MVWTYVYXTQ2EJBPBX4DZI2SDOLLY
2018/10/16 07:36:55 Current strategy: balanced
2018/10/16 07:36:55 Using network passphrase: Public Global Stellar Network ; September 2015
2018/10/16 07:36:55 No Source Account Set
2018/10/16 07:36:55 configs:
2018/10/16 07:36:55      PRICE_TOLERANCE: 0.001
2018/10/16 07:36:55      AMOUNT_TOLERANCE: 0.001
2018/10/16 07:36:55      SPREAD: 0.01
2018/10/16 07:36:55      MIN_AMOUNT_SPREAD: 0.0005
2018/10/16 07:36:55      MAX_AMOUNT_SPREAD: 0.0005
2018/10/16 07:36:55      MAX_LEVELS: 10
2018/10/16 07:36:55      LEVEL_DENSITY: 0.2
2018/10/16 07:36:55      ENSURE_FIRST_N_LEVELS: 4
2018/10/16 07:36:55      MIN_AMOUNT_CARRYOVER_SPREAD: 0.01
2018/10/16 07:36:55      MAX_AMOUNT_CARRYOVER_SPREAD: 0.01
2018/10/16 07:36:55      CARRYOVER_INCLUSION_PROBABILITY: 1
2018/10/16 07:36:55      VIRTUAL_BALANCE_BASE: 0
2018/10/16 07:36:55      VIRTUAL_BALANCE_QUOTE: 0
2018/10/16 07:36:55 ----------------------------------------------------
```
2. Start the bot using this command: ... ./kelp trade --botConf sample_trader.cfg --strategy balanced --stratConf sample_balanced.cfg
...

## Possible Solution
No idea

## Your Environment
  version: v1.0.0
  git hash: e2c473c2e866a9b27d485c403a14a4e286b51c7d
  build date: 20181015T211324Z
  GOOS: linux
  GOARCH: amd64

## Context
I am unable to run this bot 24x7 because of this bug as the kelp bot is exiting.

## Attachments
If run log is required, I can provide that. If there is any other log inside kelp, let me know. I will add it here.

**Comment by nikhilsaraf** [comment]
@PedityOfficial Thanks for filing an issue.

Kelp operates under the assumption that the horizon server you provide will always be available.  From your logs, it seems that the timing of when you faced the error coincides directly with when public horizon was down yesterday, causing your bot to crash. The behavior of the bot is _unpredictable_ when it cannot reach horizon for now -- a crash is not surprising in such a case. This is definitely an issue, one that will be addressed in due time.

It is rare that public horizon is down and it's unfortunate that this rare event occurred only a day after you started Kelp. I'm not expecting you to see this issue again if public horizon remains stable. 

I'm closing this issue for now since it's something we'll be working to fix soon. Feel free to re-open if you see this issue again.

**Comment by skirsch** [comment]
why not just catch the error and try again at the next timeout interval? Crashing seems unfriendly.

**Comment by PedityOfficial** [comment]
@nikhilsaraf , This issue happened again and as you said I am reopening this issue :)
I agree with @skirsch solution and there can be more possible solution as well. Hoping to see this gets fixed.

Log is attached here

```
2018/10/30 15:26:40 error: cannot load offers to compute liabilities for asset (native): Horizon error: "Interna
l Server Error". Check horizon.Error.Problem for more information.
2018/10/30 15:26:40 liabilities after resetting
2018/10/30 15:26:50 Can't load offers: error decoding horizon.Problem: EOF
2018/10/30 15:26:50 error: cannot load offers to compute liabilities for asset (native): error decoding horizon.
Problem: EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x75a9bb]
goroutine 1 [running]:
github.com/lightyeario/kelp/plugins.(*SDEX).logLiabilities(0xc42015c120, 0x8b18ad, 0x6, 0x0, 0x0, 0x0, 0x0)
        /Users/nikhilsaraf/dev/go/src/github.com/lightyeario/kelp/plugins/sdex.go:435 +0xfb
github.com/lightyeario/kelp/plugins.(*SDEX).LogAllLiabilities(0xc42015c120, 0x8b18ad, 0x6, 0x0, 0x0, 0x0, 0x0, 0
x8b83f4, 0x10, 0xc420244c28, ...)
        /Users/nikhilsaraf/dev/go/src/github.com/lightyeario/kelp/plugins/sdex.go:443 +0x65
github.com/lightyeario/kelp/trader.(*Trader).update(0xc420657c48)
        /Users/nikhilsaraf/dev/go/src/github.com/lightyeario/kelp/trader/trader.go:105 +0x1e9
github.com/lightyeario/kelp/trader.(*Trader).Start(0xc420657c48)
        /Users/nikhilsaraf/dev/go/src/github.com/lightyeario/kelp/trader/trader.go:67 +0x6f
github.com/lightyeario/kelp/cmd.init.4.func1(0xb447e0, 0xc420069740, 0x0, 0x6)
        /Users/nikhilsaraf/dev/go/src/github.com/lightyeario/kelp/cmd/trade.go:109 +0x9d2
github.com/lightyeario/kelp/vendor/github.com/spf13/cobra.(*Command).execute(0xb447e0, 0xc4200696e0, 0x6, 0x6, 0
xb447e0, 0xc4200696e0)
        /Users/nikhilsaraf/dev/go/src/github.com/lightyeario/kelp/vendor/github.com/spf13/cobra/command.go:702 +
0x2c6
github.com/lightyeario/kelp/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xb44e40, 0x403dfc, 0xc420072058, 
0x0)
        /Users/nikhilsaraf/dev/go/src/github.com/lightyeario/kelp/vendor/github.com/spf13/cobra/command.go:783 +
0x2e4
github.com/lightyeario/kelp/vendor/github.com/spf13/cobra.(*Command).Execute(0xb44e40, 0x0, 0x7b1582)
        /Users/nikhilsaraf/dev/go/src/github.com/lightyeario/kelp/vendor/github.com/spf13/cobra/command.go:736 +
0x2b
main.main()
        /Users/nikhilsaraf/dev/go/src/github.com/lightyeario/kelp/main.go:10 +0x2d
```
